[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ghresearcher"
version = "0.1.0"
authors = [
  {name = "Joe Hoye Dow", email = "luxunisgod123@gmail.com"}
  ] 
description = "A GitHub Code & Repo Analysis CLI for Researchers"
readme = "README.md"
license = { file = "LICENSE" }
license-files = ["LICENSE"]
keywords = ["github", "CLI", "github monitor", "github parse", "github search", "code discovery", "trending"]


requires-python = ">=3.8"
dependencies = [
    "typer>=0.25.0",
    "rich>=15.0.0",
    "textual>=8.2.5"
]

[project.scripts]
ghresearcher = "ghresearcher.cli:app"
